# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Î”H
description: > # this means to ignore newlines until "baseurl:"
  A blog about interesting stuff in IT
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://enthalpychange.github.io" # the base hostname & protocol for your site
images: "https://raw.githubusercontent.com/enthalpychange/enthalpychange.github.io/master/images"
twitter_username: ""
github_username:  ""
paginate: 5

# Build settings
markdown: kramdown

gems:
- jekyll-paginate